git add add_em.bat
git add notes.txt
git add status.bat
git add status.txt
git add tdd/sample/src/util.js
git add tdd/sample/test/util_test.js
git add tdd/server/palindrome/package.json
git add tdd/server/palindrome/src/palindrome.js
git add tdd/server/palindrome/test/palindrome-test.js
git add tdd/sample/install.bat
git add tdd/sample/package.json
git add tdd/server/palindrome/test-list.txt
