REM interactively create karma.conf.js...
node node_modules/karma/bin/karma init
REM * Testing Framework: It offers Jasmine by default.
REM    tab until you see Mocha, then hit enter... 
REM * Want to use Require.js: take default 'no'...
REM * Browser to capture: Select "Chrome" then hit _enter_ twice...
REM * Hit _enter_ to take the default for all other questions.
